###############
## 
####

GPU: [0]      #[0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'LOL_curve'
  SESSION: 'MRUNet'
# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  TRAIN_DIR: 'G:\low-light_image_enhancement\Our\dataset\LOL\our485'       # path to training data
  VAL_DIR: 'G:\low-light_image_enhancement\Our\dataset\LOL\eval15'       # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
